version: '3.2'
services:
  mysql:
    image: mysql:8.0
    command: mysqld
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      TZ: 'UTC'
    volumes:
      - ./dbdata:/var/lib/mysql/
      - ./initdb.d/:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  # api:
  #   build:
  #     context: ./
  #     dockerfile: ./cmd/api/Dockerfile
  #   volumes:
  #     - ./:/go/src/github.com/KatsuyaAkasaka/templatee_go
  #   command: go run ./cmd/api/main.go
  #   ports:
  #     - 50051:50051
  #   depends_on:
  #     - mysql
