version: '3.2'
services:
  mysql:
    image: mysql:8.0
    command: mysqld
    restart: always
    environment:
      # MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      TZ: "UTC"
    # volumes:
    #   - ./dbdata:/var/lib/mysql/
    #   - ./initdb.d/:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  stripe:
    image: stripemock/stripe-mock:v0.101.0
    ports:
      - 12111:12111
  redis:
    image: redis:6.2
    ports:
      - 6379:6379
